[[constraint]]
 name = "github.com/immesys/wave"
 source = "github.com/samkumar/wave"
 branch = "feature-jedi-delegation"

[[constraint]]
  branch = "master"
  name = "github.com/ucbrise/jedi-protocol-go"
